local colors = require('onedark.palette').dark

local M = {}

M.builtin = {
  ColorColumn = { fg = colors.fg, bg = colors.bg },
  Conceal = { fg = colors.mono_3, bg = colors.bg },
  CurSearch = { fg = colors.fg, bg = colors.accent },
  Cursor = { fg = colors.fg, bg = colors.accent },
  lCursor = { fg = colors.fg, bg = colors.accent },
  CursorIM = { fg = colors.fg, bg = colors.accent },
  CursorColumn = { bg = colors.line },
  CursorLine = { bg = colors.line },
  Directory = { fg = colors.hue_1 },
  DiffAdd = { fg = colors.added },
  DiffChange = { fg = colors.renamed },
  DiffDelete = { fg = colors.removed },
  -- DiffText = {},
  -- DiffTextAdd = {},
  EndOfBuffer = { fg = colors.bg, bg = colors.bg },
  TermCursor = { fg = colors.fg, bg = colors.accent },
  OkMsg = { fg = colors.hue_4 },
  WarningMsg = { fg = colors.hue_6 },
  ErrorMsg = { fg = colors.hue_5 },
  StderrMsg = { fg = colors.hue_5 },
  StdoutMsg = { fg = colors.fg },
  WinSeparator = { fg = colors.accent },
  -- Folded = {},
  -- FoldColumn = {},
  SignColumn = { bg = colors.bg },
  IncSearch = { fg = colors.fg, bg = colors.search_bg },
  Substitute = { fg = colors.fg, bg = colors.hue_52 },
  LineNr = { fg = colors.gutter, bg = colors.bg },
  LineNrAbove = { fg = colors.gutter, bg = colors.bg },
  LineNrBelow = { fg = colors.gutter, bg = colors.bg },
  CursorLineNr = { fg = colors.fg, bg = colors.line },
  -- CursorLineFold = {},
  CursorLineSign = { bg = colors.line },
  MatchParen = { bg = colors.guide },
  ModeMsg = { fg = colors.fg, bg = colors.line },
  MsgArea = { bg = colors.bg },
  MsgSeparator = { fg = colors.accent },
  MoreMsg = { fg = colors.hue_52 },
  NonText = { fg = colors.mono_3 },
  Normal = { fg = colors.fg, bg = colors.bg },
  NormalFloat = { fg = colors.fg },
  FloatBorder = { fg = colors.accent },
  FloatTitle = { fg = colors.fg },
  -- FloatFooter = {},
  -- NormalNC = {},
  Pmenu = { fg = colors.fg, bg = colors.line },
  PmenuSel = { fg = colors.fg, bg = colors.search_bg },
  PmenuKind = { fg = colors.fg, bg = colors.line },
  PmenuKindSel = { fg = colors.fg, bg = colors.search_bg },
  PmenuExtra = { fg = colors.fg, bg = colors.line },
  PmenuExtraSel = { fg = colors.fg, bg = colors.search_bg },
  PmenuSbar = { bg = colors.line },
  PmenuThumb = { bg = colors.search_bg },
  PmenuMatch = { bg = colors.guide },
  ComplMatchIns = { bg = colors.guide },
  Question = { fg = colors.hue_2 },
  QuickFixLine = { fg = colors.hue_2 },
  -- FloatShadow = {},
  -- FloatShadowThrough = {},
  Search = { fg = colors.fg, bg = colors.search_bg },
  -- SnippetTabstop = {},
  SpecialKey = { fg = colors.mono_3 },
  SpellBad = { sp = colors.hue_52, undercurl = true },
  SpellCap = { sp = colors.hue_62, undercurl = true },
  SpellLocal = { sp = colors.hue_4, undercurl = true },
  SpellRare = { sp = colors.hue_1, undercurl = true },
  StatusLine = { bg = colors.line },
  StatusLineNC = { bg = colors.line },
  StatusLineTerm = { bg = colors.line },
  Visual = { bg = colors.selection },
  VisualNOS = { bg = colors.selection },
  Whitespace = { sp = colors.mono_3, undercurl = true },
  -- WildMenu = {},
  -- WinBar = {},
  -- WinBarNC = {},
}

-- Builtin syntax groups
M.syntax = {
  Comment = { fg = colors.mono_3, italic = true },
  Constant = { fg = colors.hue_6 },
  String = { fg = colors.hue_4 },
  Character = { fg = colors.hue_4 },
  Number = { fg = colors.hue_6 },
  Boolean = { fg = colors.hue_3 },
  Float = { fg = colors.hue_6 },
  Identifier = { fg = colors.fg },
  Function = { fg = colors.hue_2 },
  Statement = { fg = colors.hue_3 },
  Conditional = { fg = colors.hue_3 },
  Repeat = { fg = colors.hue_3 },
  Label = { fg = colors.hue_3, bold = true },
  Operator = { fg = colors.fg },
  Keyword = { fg = colors.hue_3 },
  Exception = { fg = colors.hue_3 },
  PreProc = { fg = colors.hue_62 },
  Include = { fg = colors.hue_3 },
  Define = { fg = colors.hue_3 },
  Macro = { fg = colors.hue_2 },
  PreCondit = { fg = colors.hue_3 },
  Type = { fg = colors.hue_3 },
  StorageClass = { fg = colors.fg },
  Structure = { fg = colors.hue_3 },
  Typedef = { fg = colors.hue_1 },
  Special = { fg = colors.hue_1 },
  SpecialChar = { fg = colors.hue_1 },
  Tag = { bg = colors.hue_2 },
  Delimiter = { fg = colors.hue_4 },
  SpecialComment = { fg = colors.mono_3, italic = true },
  Debug = { fg = colors.hue_3 },
  Underlined = { fg = colors.hue_2, underline = true },
  Ignore = { bg = colors.hue_52 },
  Error = { sp = colors.hue_5, undercurl = true },
  Todo = { fg = colors.hue_6, bold = true },
  Added = { fg = colors.added },
  Changed = { fg = colors.renamed },
  Removed = { fg = colors.removed }
}

M.diagnostic = {
  DiagnosticError = { fg = colors.hue_52 },
  DiagnosticWarn = { fg = colors.hue_62 },
  DiagnosticInfo = { fg = colors.hue_1 },
  DiagnosticHint = { fg = colors.hue_3},
  DiagnosticOk = { fg = colors.hue_4 },
  DiagnosticVirtualTextError = { fg = colors.hue_52 },
  DiagnosticVirtualTextWarn = { fg = colors.hue_62},
  DiagnosticVirtualTextInfo = { fg = colors.hue_1 },
  DiagnosticVirtualTextHint = { fg = colors.hue_3 },
  DiagnosticVirtualTextOk = { fg = colors.hue_4 },
  -- DiagnosticVirtualLinesError = {},
  -- DiagnosticVirtualLinesWarn = {},
  -- DiagnosticVirtualLinesInfo = {},
  -- DiagnosticVirtualLinesHint = {},
  -- DiagnosticVirtualLinesOk = {},
  DiagnosticUnderlineError = { sp = colors.hue_52, undercurl = true },
  DiagnosticUnderlineWarn = { sp = colors.hue_62, undercurl = true },
  DiagnosticUnderlineInfo = { sp = colors.hue_1, undercurl = true },
  DiagnosticUnderlineHint = { sp = colors.hue_3, undercurl = true },
  DiagnosticUnderlineOk = { sp = colors.hue_4, undercurl = true },
  DiagnosticFloatingError = { fg = colors.hue_52 },
  DiagnosticFloatingWarn = { fg = colors.hue_62 },
  DiagnosticFloatingInfo = { fg = colors.hue_1 },
  DiagnosticFloatingHint = { fg = colors.hue_3 },
  DiagnosticFloatingOk = { fg = colors.hue_4 },
  DiagnosticSignError = { fg = colors.hue_52 },
  DiagnosticSignWarn = { fg = colors.hue_62 },
  DiagnosticSignInfo = { fg = colors.hue_1 },
  DiagnosticSignHint = { fg = colors.hue_3 },
  DiagnosticSignOk = { fg = colors.hue_4 },
  DiagnosticDeprecated = { fg = colors.hue_5 }, -- TODO; check original theme spec
  DiagnosticUnnecessary = { fg = colors.mono_3 }
}

-- Treesitter
M.treesitter = {
  ['@attribute'] = { fg = colors.hue_62 },
  ['@attribute.builtin'] = { fg = colors.hue_62 },

  ['@boolean'] = { fg = colors.hue_3 },

  ['@character'] = { fg = colors.hue_4 },
  ['@character.special'] = { fg = colors.hue_4 },

  ['@comment'] = { fg = colors.mono_3, italic = true },
  ['@comment.documentation'] = { fg = colors.mono_3 },
  ['@comment.error'] = { fg = colors.hue_6 },
  ['@comment.warning'] = { fg = colors.hue_6 },
  ['@comment.todo'] = { fg = colors.hue_6 },
  ['@comment.note'] = { fg = colors.hue_6 },

  ['@constant'] = { fg = colors.hue_6 },
  ['@constant.builtin'] = { fg = colors.hue_6 },
  ['@constant.macro'] = { fg = colors.hue_6 },

  ['@constructor'] = { fg = colors.hue_3 },

  ['@diff.plus'] = { fg = colors.added},
  ['@diff.minus'] = { fg = colors.removed},
  ['@diff.delta'] = { fg = colors.renamed},

  ['@function'] = { fg = colors.hue_2 },
  ['@function.builtin'] = { fg = colors.hue_2 },
  ['@function.call'] = { fg = colors.hue_2 },
  ['@function.macro'] = { fg = colors.hue_2 },
  ['@function.method'] = { fg = colors.hue_2 },
  ['@function.method.call'] = { fg = colors.hue_2 },

  ['@keyword'] = { fg = colors.hue_3 },
  ['@keyword.coroutine'] = { fg = colors.hue_3 },
  ['@keyword.function'] = { fg = colors.hue_3 },
  ['@keyword.operator'] = { fg = colors.hue_3 },
  ['@keyword.import'] = { fg = colors.hue_3 },
  ['@keyword.type'] = { fg = colors.hue_3 },
  ['@keyword.modifier'] = { fg = colors.hue_3 },
  ['@keyword.repeat'] = { fg = colors.hue_3 },
  ['@keyword.return'] = { fg = colors.hue_3 },
  ['@keyword.debug'] = { fg = colors.hue_3 },
  ['@keyword.exception'] = { fg = colors.hue_3 },
  ['@keyword.conditional'] = { fg = colors.hue_3 },
  ['@keyword.conditional.ternary'] = { fg = colors.fg },
  ['@keyword.directive'] = { fg = colors.hue_3 },
  ['@keyword.directive.define'] = { fg = colors.hue_3 },

  ['@label'] = { fg = colors.hue_3, bold = true },
  ["@markup.strong"] = { fg = colors.fg, bold = true },
  ["@markup.italic"] = { fg = colors.fg, italic = true },
  ["@markup.strikethrough"] = { fg = colors.fg, strikethrough = true },
  ["@markup.underline"] = { fg = colors.fg, underline = true },
  ["@markup.heading"] = { fg = colors.hue_6, bold = true },
  ["@markup.heading.1"] = { fg = colors.hue_5, bold = true },
  ["@markup.heading.2"] = { fg = colors.hue_3, bold = true },
  ["@markup.heading.3"] = { fg = colors.hue_6, bold = true },
  ["@markup.heading.4"] = { fg = colors.hue_5, bold = true },
  ["@markup.heading.5"] = { fg = colors.hue_3, bold = true },
  ["@markup.heading.6"] = { fg = colors.hue_6, bold = true },
  ["@markup.link"] = { fg = colors.hue_2 },
  ["@markup.link.label"] = { fg = colors.hue_1, bold = true },
  ["@markup.link.url"] = { fg = colors.hue_1, underline = true },
  ["@markup.list"] = { fg = colors.hue_5 },
  ["@markup.list.checked"] = { fg = colors.hue_4 },
  ["@markup.list.unchecked"] = { fg = colors.hue_5 },
  ["@markup.math"] = { fg = colors.fg },
  ["@markup.quote"] = { fg = colors.mono_3, italic = true },
  ["@markup.raw"] = { fg = colors.hue_4 },
  ["@markup.raw.block"] = { fg = colors.hue_4 },

  ['@module'] = { fg = colors.hue_3 },
  ['@module.builtin'] = { fg = colors.hue_3 },

  ['@number'] = { fg = colors.hue_6 },
  ['@number.float'] = { fg = colors.hue_6 },

  ['@operator'] = { fg = colors.fg },

  ['@punctuation.delimiter'] = { fg = colors.fg },
  ['@punctuation.bracket'] = { fg = colors.fg },
  ['@punctuation.special'] = { fg = colors.fg },

  ['@string'] = { fg = colors.hue_4 },
  ['@string.documentation'] = { fg = colors.hue_4 },
  ['@string.regexp'] = { fg = colors.hue_1 },
  ['@string.escape'] = { fg = colors.hue_4 },
  ['@string.special'] = { fg = colors.hue_4 },
  ['@string.special.symbol'] = { fg = colors.hue_4 },
  ['@string.special.path'] = { fg = colors.hue_4, underline = true },
  ['@string.special.url'] = { fg = colors.hue_4, underline = true },

  ['@tag'] = { fg = colors.hue_5 },
  ['@tag.builtin'] = { fg = colors.hue_5 },
  ['@tag.attribute'] = { fg = colors.hue_6 },
  ['@tag.delimiter'] = { fg = colors.fg },

  ['@type'] = { fg = colors.hue_3 },
  ['@type.builtin'] = { fg = colors.hue_3 },
  ['@type.definition'] = { fg = colors.hue_3 },

  ['@variable'] = { fg = colors.hue_6 },
  ['@variable.builtin'] = { fg = colors.hue_3 },
  ['@variable.parameter'] = { fg = colors.hue_6 },
  ['@variable.parameter.builtin'] = { fg = colors.hue_5 },
  ['@variable.member'] = { fg = colors.hue_5 },

  ['@property'] = { fg = colors.hue_6}
}

M.lsp = {
  ['@lsp.type.class'] = { fg = colors.hue_62 },
  ['@lsp.type.comment'] = { fg = colors.mono_3, italic = true },
  ['@lsp.type.decorator'] = { fg = colors.hue_62 },
  ['@lsp.type.enum'] = { fg = colors.hue_62 },
  ['@lsp.type.enumMember'] = { fg = colors.hue_5 },
  ['@lsp.type.event'] = { bg = colors.hue_6 },
  ['@lsp.type.function'] = { fg = colors.hue_2 },
  ['@lsp.type.interface'] = { fg = colors.hue_62 },
  ['@lsp.type.keyword'] = { fg = colors.hue_3 },
  ['@lsp.type.macro'] = { bg = colors.hue_3 },
  ['@lsp.type.method'] = { fg = colors.hue_2 },
  ['@lsp.type.modifier'] = { bg = colors.hue_2 },
  ['@lsp.type.namespace'] = { fg = colors.hue_6 },
  ['@lsp.type.number'] = { fg = colors.hue_6 },
  ['@lsp.type.operator'] = { fg = colors.fg },
  ['@lsp.type.parameter'] = { fg = colors.hue_6 },
  ['@lsp.type.property'] = { fg = colors.hue_5 },
  ['@lsp.type.regexp'] = { fg = colors.hue_1 },
  ['@lsp.type.string'] = { fg = colors.hue_4 },
  ['@lsp.type.struct'] = { fg = colors.hue_6 },
  ['@lsp.type.typeParameter'] = { fg = colors.hue_3 },
  ['@lsp.type.variable'] = { fg = colors.hue_6 },

  ['@lsp.mod.abstract'] = { fg = colors.hue_52 },
  ['@lsp.mod.async'] = { fg = colors.hue_2 },
  ['@lsp.mod.deprecated'] = { fg = colors.modified, bg = colors.line },
  ['@lsp.mod.modification'] = { bg = colors.mono_2 },

  -- HTML
  ['htmlTag'] = { fg = colors.fg },
  ['htmlTagName'] = { fg = colors.hue_5 },
  ['htmlTagN'] = { fg = colors.hue_5 },
  ['htmlArg'] = { fg = colors.hue_6 },

  -- CSS
  ['cssAtKeyword'] = { fg = colors.hue_3 },
  ['cssAttrComma'] = { fg = colors.fg },
  ['cssAttrRegion'] = { fg = colors.hue_6 },
  ['cssBraces'] = { fg = colors.fg },
  ['cssClassName'] = { fg = colors.hue_6 },
  ['cssClassNameDot'] = { fg = colors.fg },
  ['cssCustomProp'] = { fg = colors.fg },
  ['cssImportant'] = { fg = colors.hue_3 },
  ['cssPseudoClass'] = { fg = colors.hue_1 },
  ['cssPseudoClassId'] = { fg = colors.hue_1 },
  ['cssTagName'] = { fg = colors.hue_5 },

  -- SASS
  ['sassClass'] = { fg = colors.fg },
  ['sassClassChar'] = { fg = colors.hue_6 },
  ['sassId'] = { fg = colors.hue_2 },
  ['sassIdChar'] = { fg = colors.hue_2 },

  -- JavaScript
  ['javaScriptBraces'] = { fg = colors.fg },

  -- JSON
  ['jsonBraces'] = { fg = colors.fg },
  ['jsonKeyword'] = { fg = colors.hue_5 },

  -- Typescript
  ['@lsp.type.type.typescript'] = { fg = colors.hue_62 },
  ['typescriptAbstract'] = { fg = colors.hue_3 },
  ['typescriptAmbientDeclaration'] = { fg = colors.hue_3 },
  ['typescriptArrowFunc'] = { fg = colors.fg },
  ['typescriptBraces'] = { fg = colors.fg },
  ['typescriptClassName'] = { fg = colors.hue_6 },
  ['typescriptClassStatic'] = { fg = colors.hue_3 },
  ['typescriptDecorator'] = { fg = colors.hue_62 },
  ['typescriptDocNotation'] = { fg = colors.hue_3 },
  ['typescriptDocTags'] = { fg = colors.hue_3 },
  ['typescriptDOMEventProp'] = { fg = colors.hue_5 },
  ['typescriptEndColons'] = { fg = colors.fg },
  ['typescriptEnum'] = { fg = colors.hue_62 },
  ['typescriptEnumKeyword'] = { fg = colors.hue_3 },
  ['typescriptExport'] = { fg = colors.hue_3 },
  ['typescriptFuncCallArg'] = { fg = colors.fg },
  ['typescriptHeadersMethod'] = { fg = colors.hue_2 },
  ['typescriptImport'] = { fg = colors.hue_3 },
  ['typescriptInterfaceName'] = { fg = colors.hue_62 },
  ['typescriptMember'] = { fg = colors.hue_5 },
  ['typescriptMethodAccessor'] = { fg = colors.hue_3 },
  ['typescriptObjectLabel'] = { fg = colors.hue_5 },
  ['typescriptProp'] = { fg = colors.hue_2 },
  ['typescriptRegexpBoundary'] = { fg = colors.hue_3 },
  ['typescriptRegexpCharClass'] = { fg = colors.hue_6 },
  ['typescriptRegexpGroup'] = { fg = colors.hue_1 },
  ['typescriptRegexpMod'] = { fg = colors.hue_1 },
  ['typescriptRegexpOr'] = { fg = colors.hue_3 },
  ['typescriptRegexpString'] = { fg = colors.hue_1 },
  ['typescriptRegexpQuantifier'] = { fg = colors.hue_6 },
  ['typescriptTypeParameter'] = { fg = colors.hue_62 },
  ['typescriptTypeReference'] = { fg = colors.hue_62 },
  ['typescriptVariable'] = { fg = colors.hue_3 },
  ['typescriptUnion'] = { fg = colors.fg },

  -- Ruby
  ['rubyBlockParameterList'] = { fg = colors.hue_6 },
  ['rubyClassBlock'] = { },
  ['rubyClassName'] = { fg = colors.hue_6 },
  ['rubyConstant'] = { fg = colors.hue_6 },
  ['rubyHeredocDelimiter'] = { fg = colors.hue_3 },
  ['rubyInclude'] = { fg = colors.hue_2 },
  ['rubyInstanceVariable'] = { fg = colors.hue_5 },
  ['rubyInterpolationDelimiter'] = { fg = colors.hue_5 },
  ['rubyKeywordAsMethod'] = { fg = colors.hue_2 },
  ['rubyMethodBlock'] = { fg = colors.fg },
  ['rubyRegexp'] = { fg = colors.hue_1 },
  ['rubySymbol'] = { fg = colors.hue_1 },
}

M.plugins = {
  -- Indent Blanklines
  ['IblIndent'] = { fg = colors.guide },
  ['IblWhitespace'] = { fg = colors.guide },
  ['IblScope'] = { fg = colors.mono_3 },
}

return M
